// The coastline as generated geometry: one continuous ribbon per island.
//
//   - The outline is `shoreCurve.ts`'s smooth closed curve: the coast loop
//     pushed out to sea and run through a cubic B-spline wider than a hex edge,
//     so no straight segments survive. Its arc-length sine modulation is
//     present but at amplitude zero. See that file.
//   - The cross-section is a continuous slope from the dry crest at land height
//     to a foot below the lowest trough, so the water meets sand at every
//     height it reaches.
//   - The dry/wet material seam is the same curve inset by a constant fraction
//     of the ribbon's local width.
//
// Colour comes from beach.glb's Mat_Shore_sand and Mat_Shore_wetsand, so
// palette.json controls the look.
//
// The blend carries a canonical strip and wedge (`Beach_*`, generated by
// tools/blender/lattice.py from the constants at the bottom of this file) for
// modelling terrain against the coast. The renderer does not draw them; see
// `beachStripGeometry`.
import * as THREE from "three";
import { LATTICE_SIZE } from "./coords";
import type { CoastLoop, Vec2 } from "./coastline";
import {
  SHORE_SMOOTH_PULL,
  SHORE_SWELL,
  shoreStations,
  wetLineU,
  type ShoreStation,
} from "./shoreCurve";

/**
 * Distance from a water hex's centre to the middle of an edge.
 *
 * LATTICE_SIZE, not HEX_SIZE: the beach is measured from the shared lattice
 * line, and water tiles are drawn a full lattice cell wide (see LATTICE_SCALE).
 * Using the art's smaller size leaves a blue hairline round the island.
 */
export const APOTHEM = (LATTICE_SIZE * Math.sqrt(3)) / 2;

/**
 * The top of the beach, just under the gutter sand rather than level with the
 * land.
 *
 * A land tile's top is at 0.25 and the gutter sand (`SAND_Y` in
 * gapGeometry.ts) at 0.22. Starting level with the tile covered the gutters and
 * tile rims round the island; 0.215 passes just under them so they stay visible.
 *
 * Also the sea's ceiling, so `ocean.ts` imports it. See `OCEAN_CREST_CEILING`
 * and `WAVE_MAX_AMPLITUDE`.
 */
export const TOP_Y = 0.215;

/**
 * The height of the mean waterline, which the rest of the board is cut against.
 *
 * `SURFACE.sea` is the sea's mean; ships float at it and the far ocean lies at
 * it. The beach is built to pass through it, and `ocean.ts` lowers the wave
 * sheet (`WAVE_DROP`) so its mean lands here.
 */
export const WATER_Y = 0.13;

/**
 * The submerged foot of the sand.
 *
 * The sand continues below the mean waterline so troughs uncover more sand
 * instead of a vertical wall.
 *
 * Raising the foot above zero shortens the fall, giving the wanted slope on a
 * 1.6 reach instead of a 2.0 one that would close a one-hex strait and fold a
 * one-hex pond (see `a narrow beach leaves a one-hex strait open` and
 * shoreCurve.test.ts).
 *
 * It must stay below the deepest trough, `OCEAN_MIN_Y` (0.072 at the tuned
 * amplitude), leaving 0.022. A bigger swell needs this lowered. `ocean.test.ts`
 * checks the pair, since this file cannot import ocean.ts.
 */
export const BEACH_FOOT_Y = 0.05;

/**
 * How far the sand reaches from the lattice line into the water, at nominal
 * width before modulation. A visual choice: 0.86 of visible sand at mean tide.
 *
 * The limit is not the apothem. A row of water hexes pinches at the lattice
 * edge between two of them, where headlands are only LATTICE_SIZE (3.144)
 * apart. On a one-hex strait the submerged feet leave 1.59 of open water at a
 * reach of 1.0, 0.72 at 1.4, 0.30 at 1.6, and meet at about 1.75. A one-hex
 * pond's ribbon exceeds the smoothness bound at about 1.70 and escapes
 * `BEACH_ENVELOPE` at 1.95.
 *
 * So the ceiling is about 1.7, measured. For a gentler beach past that, use
 * `BEACH_FOOT_Y` or `BEACH_SHAPE`. See `a narrow beach leaves a one-hex strait
 * open` here and the pond checks in `shoreCurve.test.ts`.
 */
export const BEACH_REACH = 1.6;

/**
 * The furthest from the lattice line any sand can be; what the scene reserves.
 *
 * A bay's mitre is further from the corner than the reach but still exactly
 * `reach` from each edge, so `MITRE` does not apply. Smoothing moves a point
 * toward the inside of its turn: inward at a headland, outward at a bay.
 *
 * A corner turning `theta` puts its smoothed mitre `BEACH_REACH + (7/30) *
 * SHORE_SMOOTH * sin(theta)` from the coast, which peaks at 90 degrees, so
 * `BEACH_REACH + SHORE_SMOOTH_PULL` (1.327) bounds every corner angle. Hex
 * boundaries turn only 60 degrees, giving 1.283; the worst case measured over
 * the shot board and 1,500 random ones is 1.2832 (adjacent bays can share a
 * smoothing window and add).
 *
 * `SHORE_SWELL` is a factor because the modulation scales a cross-section
 * (`shoreStations`) rather than extending it. At amplitude zero it is 1.
 */
export const BEACH_ENVELOPE = (BEACH_REACH + SHORE_SMOOTH_PULL) * (1 + SHORE_SWELL / BEACH_REACH);

/**
 * How far the ribbon runs back landward of the lattice line, under the gutter.
 *
 * Butting the ribbon against the gutter sand (`SAND_Y`) at the lattice line
 * leaves a seam along each tile rim; running the lip back under the gutter
 * hides it. Kept well short of the gutter's 0.125 half-width so the lip stops
 * short of the tile itself.
 */
export const BEACH_TUCK = 0.03;

/**
 * The height of the wet sand's upper edge: above it the ribbon uses
 * Mat_Shore_sand, below it Mat_Shore_wetsand.
 *
 * Set at the top of the swash, 0.02 above the mean (the crest lifts the sea up
 * to 0.053 above it). At 0.15 the split is 0.67 dry to 0.19 exposed wet, a
 * thin dark line at the water's edge. `the wet band is a line at the water's
 * edge` checks the ratio.
 */
export const BEACH_WET_TOP_Y = 0.15;

/**
 * How much of the profile's fall is linear versus quadratic.
 *
 * At 1 the ribbon is a flat ramp, which reads as a cone with a crease where it
 * meets land; at 0 it is a parabola whose top is nearly level. 0.9 is almost a
 * straight fall (5.3 degrees at the crest, 6.5 at the foot), with a little
 * curvature to soften the crease.
 *
 * The waterline travels two thirds of the ribbon between extreme crest and
 * trough, and about a tenth over the swell's RMS range.
 */
export const BEACH_SHAPE = 0.9;

/** Underside of the ribbon. Buried in the sea tile's hull, which is at -0.03. */
const BOTTOM_Y = -0.06;

export type SandKind = "dry" | "wet";

/**
 * The beach's height at fraction `u` of the way across it. A fraction because
 * the ribbon's width varies: the profile is the same everywhere, and a wider
 * stretch is simply gentler.
 */
export function beachProfileY(u: number): number {
  const c = Math.min(1, Math.max(0, u));
  const fall = BEACH_SHAPE * c + (1 - BEACH_SHAPE) * c * c;
  return TOP_Y + (BEACH_FOOT_Y - TOP_Y) * fall;
}

/**
 * The inverse: how far out the sand is at a given height. Used by
 * ocean.test.ts to locate the waterline for the sea's ceiling and floor.
 */
export function beachProfileU(y: number): number {
  const fall = (TOP_Y - y) / (TOP_Y - BEACH_FOOT_Y);
  const a = 1 - BEACH_SHAPE;
  const u = (-BEACH_SHAPE + Math.sqrt(BEACH_SHAPE * BEACH_SHAPE + 4 * a * fall)) / (2 * a);
  return Math.min(1, Math.max(0, u));
}

/** The stations one loop of coast is built on. See `shoreCurve.ts`. */
export function shoreSamples(loop: CoastLoop): ShoreStation[] {
  return shoreStations(loop, BEACH_REACH, BEACH_TUCK);
}

/**
 * A point on a station's cross-section, `u` of the way from the coast to the
 * foot. The only place the ribbon's local width is used.
 */
export function shorePointAt(s: ShoreStation, u: number): Vec2 {
  return [s.base[0] + (s.foot[0] - s.base[0]) * u, s.base[1] + (s.foot[1] - s.base[1]) * u];
}

/** How far the sand reaches at a station, perpendicular measure aside. */
export function shoreReach(s: ShoreStation): number {
  return Math.hypot(s.foot[0] - s.base[0], s.foot[1] - s.base[1]);
}

/** Where the sand stops being dry at a station, as a fraction across it. */
export function shoreWetU(s: ShoreStation): number {
  return wetLineU(s, beachProfileU(BEACH_WET_TOP_Y));
}

/** A vertex of the ribbon: a point on the surface, in world space. */
type Row = [number, number, number];

/**
 * The rows of one cross-section, landward to seaward.
 *
 * Seven rows, two materials: dry sand is the lip's skirt, lip, crest and wet
 * line; wet sand is the wet line, a middle row, the foot and the foot's skirt.
 * The wet line is shared, so the material boundary is a single curve.
 */
function crossSection(s: ShoreStation): Row[] {
  const wet = shoreWetU(s);
  const mid = (wet + 1) / 2;
  const at = (u: number): Row => {
    const p = shorePointAt(s, u);
    return [p[0], beachProfileY(u), p[1]];
  };
  return [
    [s.lip[0], BOTTOM_Y, s.lip[1]],
    [s.lip[0], TOP_Y, s.lip[1]],
    at(0),
    at(wet),
    at(mid),
    at(1),
    [s.foot[0], BOTTOM_Y, s.foot[1]],
  ];
}

/** Which rows each material spans. The wet line, row 3, is the seam. */
const BANDS: Readonly<Record<SandKind, [number, number]>> = {
  dry: [0, 3],
  wet: [3, 6],
};

/** Cross-product area of a triangle, doubled. Zero for the collapsed ones. */
function degenerate(a: Row, b: Row, c: Row): boolean {
  const ux = b[0] - a[0];
  const uy = b[1] - a[1];
  const uz = b[2] - a[2];
  const vx = c[0] - a[0];
  const vy = c[1] - a[1];
  const vz = c[2] - a[2];
  const cx = uy * vz - uz * vy;
  const cy = uz * vx - ux * vz;
  const cz = ux * vy - uy * vx;
  return cx * cx + cy * cy + cz * cz < 1e-18;
}

/**
 * How far landward of the coast `shoreSegmentLand` probes for the hex a stretch
 * of ribbon belongs to: well inside the land hex's cell, short of its centre.
 */
export const SHORE_PROBE = 0.4;

/**
 * The point a stretch of ribbon, between two consecutive stations, is owned
 * from: the mid-point of their coast points, stepped `SHORE_PROBE` back toward
 * the land along the stations' mean direction.
 *
 * Every station's base is on its own land hex's rim (a lattice line, or a
 * corner of it), and its foot lies seaward, so the probe lands in the cell of
 * the land hex that stretch of sand is the beach of. At a bay, where two land
 * hexes meet the water at one corner, the stretch straddling the corner goes
 * to either.
 */
export function shoreSegmentLand(a: ShoreStation, b: ShoreStation): Vec2 {
  const bx = (a.base[0] + b.base[0]) / 2;
  const bz = (a.base[1] + b.base[1]) / 2;
  const fx = (a.foot[0] + b.foot[0]) / 2;
  const fz = (a.foot[1] + b.foot[1]) / 2;
  const len = Math.hypot(fx - bx, fz - bz) || 1;
  return [bx - ((fx - bx) / len) * SHORE_PROBE, bz - ((fz - bz) / len) * SHORE_PROBE];
}

/**
 * Which stretches of the ribbon a build keeps, given the two stations at its
 * ends. Absent, all of it.
 *
 * The fog layer uses it to split the ribbon in two: the sand of known land,
 * and the shore of a fog hex, drawn as cloud (see `layers/fog.ts`). The
 * cross-sections are the same in both builds, so where one stops the other
 * starts with no seam or step.
 */
export type ShoreFilter = (a: ShoreStation, b: ShoreStation) => boolean;

/**
 * The ribbon, as one buffer per material for the whole board.
 *
 * World space and not instanced: the curve is smoothed along the whole loop,
 * so no two stretches share a mesh. Built once per board, a few thousand
 * triangles.
 *
 * Wound counter-clockwise seen from above so top faces light correctly. The
 * two skirts drop to `BOTTOM_Y` inside the sea tile's hull and the gutter's
 * slab, closing the ribbon without a bottom face.
 */
export function beachRibbonGeometry(
  loops: CoastLoop[],
  kind: SandKind,
  only?: ShoreFilter,
): THREE.BufferGeometry {
  const pos: number[] = [];
  const [from, to] = BANDS[kind];
  const tri = (a: Row, b: Row, c: Row) => {
    if (degenerate(a, b, c)) return;
    pos.push(a[0], a[1], a[2], b[0], b[1], b[2], c[0], c[1], c[2]);
  };

  for (const loop of loops) {
    const samples = shoreSamples(loop);
    if (samples.length < 3) continue;
    const sections = samples.map(crossSection);
    for (let i = 0; i < sections.length; i++) {
      const here = sections[i];
      const next = sections[(i + 1) % sections.length];
      if (only && !only(samples[i], samples[(i + 1) % samples.length])) continue;
      for (let r = from; r < to; r++) {
        tri(here[r], next[r], next[r + 1]);
        tri(here[r], next[r + 1], here[r + 1]);
      }
    }
  }

  const geo = new THREE.BufferGeometry();
  geo.setAttribute("position", new THREE.Float32BufferAttribute(pos, 3));
  // Flat shading to match the faceted board. Non-indexed geometry gives each
  // triangle its own vertices, so nothing averages across facets.
  geo.computeVertexNormals();
  return geo;
}

// ---------------------------------------------------------------------------
// The reference cross-section, mirrored into the blend.
//
// Everything below draws the two-band reference strip and its corner wedge.
// The renderer does not use them; `tools/blender/lattice.py` builds the same
// shapes in the blend for modelling against, and `assetAnchors.test.ts` holds
// the shipped copy to these. Kept unchanged because beach.glb cannot be
// regenerated from here, and they remain a valid envelope for the exposed sand
// (0.62 from crest to mean waterline against the prism's 1.4025). Regenerating
// against the ribbon is an art-pipeline job (`make apply-edits`).
// ---------------------------------------------------------------------------

/**
 * Facets across the reference wedge's corner: one, a single chamfer. Mirrored
 * into the blend and pinned by `tools/blender/test_lattice.py`.
 */
const CORNER_FACETS = 1;

/** The pale apron of the reference cross-section. */
export const DRY_WIDTH = 0.7975;

/** Its shelf, from the land's 0.25 down to the waterline's 0.13. */
export const WET_WIDTH = 0.605;

/** How far the reference cross-section reaches. */
export const BEACH_WIDTH = DRY_WIDTH + WET_WIDTH;

/** A point on the reference top surface. */
interface Top {
  x: number;
  z: number;
  y: number;
}

/** Extrude a convex top polygon down to a flat bottom. */
function prism(top: Top[]): THREE.BufferGeometry {
  const pos: number[] = [];
  const tri = (a: Top, b: Top, c: Top) => {
    pos.push(a.x, a.y, a.z, b.x, b.y, b.z, c.x, c.y, c.z);
  };
  const floor = (p: Top): Top => ({ x: p.x, z: p.z, y: BOTTOM_Y });

  for (let i = 1; i + 1 < top.length; i++) tri(top[0], top[i], top[i + 1]);
  for (let i = 1; i + 1 < top.length; i++) tri(floor(top[0]), floor(top[i + 1]), floor(top[i]));
  for (let i = 0; i < top.length; i++) {
    const a = top[i];
    const b = top[(i + 1) % top.length];
    tri(a, b, floor(b));
    tri(a, floor(b), floor(a));
  }

  const geo = new THREE.BufferGeometry();
  geo.setAttribute("position", new THREE.Float32BufferAttribute(pos, 3));
  geo.computeVertexNormals();
  return geo;
}

/** How far out from the shoreline each band of the reference section runs. */
function span(kind: SandKind): [number, number] {
  return kind === "dry" ? [0, DRY_WIDTH] : [DRY_WIDTH, BEACH_WIDTH];
}

/** The reference section's height at distance `t` out from the shoreline. */
export function beachHeightAt(t: number): number {
  if (t <= DRY_WIDTH) return TOP_Y;
  const shelf = (t - DRY_WIDTH) / WET_WIDTH;
  return TOP_Y + (WATER_Y - TOP_Y) * shelf;
}

/** The reference strip for edge 0, the +x edge of a water hex at the origin. */
export function beachStripGeometry(kind: SandKind): THREE.BufferGeometry {
  const [from, to] = span(kind);
  const half = LATTICE_SIZE / 2; // half an edge's length
  const near = APOTHEM - from;
  const far = APOTHEM - to;
  return prism([
    { x: near, z: -half, y: beachHeightAt(from) },
    { x: near, z: half, y: beachHeightAt(from) },
    { x: far, z: half, y: beachHeightAt(to) },
    { x: far, z: -half, y: beachHeightAt(to) },
  ]);
}

/** The reference wedge for corner 0, the vertex between edge 0 and edge 1. */
export function beachConnectorGeometry(kind: SandKind): THREE.BufferGeometry {
  const [from, to] = span(kind);
  const apex = { x: APOTHEM, z: LATTICE_SIZE / 2 };
  // Angles are measured from +x toward +z. The edge-0 strip ends square across
  // the vertex, filling 180 to 270 degrees; the far strip fills 30 to 120. The
  // wedge fills the remaining 120 to 180.
  const START = (2 * Math.PI) / 3;
  const SWEEP = Math.PI / 3;

  const at = (angle: number, radius: number): Top => ({
    x: apex.x + Math.cos(angle) * radius,
    z: apex.z + Math.sin(angle) * radius,
    y: beachHeightAt(radius),
  });

  const outer: Top[] = [];
  const inner: Top[] = [];
  for (let i = 0; i <= CORNER_FACETS; i++) {
    const angle = START + (SWEEP * i) / CORNER_FACETS;
    outer.push(at(angle, to));
    inner.push(at(angle, from));
  }
  // A dry wedge reaches the vertex itself, so its inner edge is a single point;
  // collapsing it avoids a sliver of degenerate triangles there.
  const innerRing = from === 0 ? [{ ...apex, y: beachHeightAt(0) }] : inner.slice().reverse();
  return prism([...outer, ...innerRing]);
}
