// The Raiders castle tile, measured off the shipped file.
//
// `tools/blender/hexcontract.py` is the standard every hex holds (slab size,
// gutter, chip keep-clear disc, prop ceiling), enforced by `make check-hexes`.
// That needs Blender, which is not in the flake, so no gate runs it. This tile
// is generated by a script (`tools/blender/gen/castle.py`), so the clearances
// are re-measured here on the shipped file.
//
// Read straight from the GLB like `scenarioArt.test.ts` and
// `knightSwordArt.test.ts`, since the loader needs WebGL.
import { test, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { TILES } from "./manifest.generated";
import { tileScale } from "./layers/tiles";
import { CASTLE_TILE } from "./loader";
import { PLAIN_MODELS } from "@/testGlbFixtures";

// The plain copies: what ships is meshopt-encoded, and this parses the
// container. See testGlbFixtures.ts.
const MODELS = PLAIN_MODELS;

const CASTLE = "tiles/castle.glb";

interface Gltf {
  meshes: {
    name?: string;
    primitives: { attributes: Record<string, number>; indices?: number }[];
  }[];
  nodes: {
    name?: string;
    mesh?: number;
    translation?: number[];
    scale?: number[];
    rotation?: number[];
  }[];
  accessors: {
    bufferView: number;
    byteOffset?: number;
    componentType: number;
    count: number;
    type: string;
    min?: number[];
    max?: number[];
  }[];
  bufferViews: { byteOffset?: number; byteLength: number; byteStride?: number }[];
  materials?: { name?: string }[];
}

function readGlb(file: string): { gltf: Gltf; bin: Buffer } {
  const buf = readFileSync(join(MODELS, file));
  expect(buf.readUInt32LE(0), `${file} is not a GLB`).toBe(0x46546c67);
  const jsonLen = buf.readUInt32LE(12);
  const gltf = JSON.parse(buf.subarray(20, 20 + jsonLen).toString("utf8")) as Gltf;
  // The BIN chunk follows the JSON chunk, each with an 8-byte header.
  const binHeader = 20 + jsonLen;
  expect(buf.readUInt32LE(binHeader + 4), "second chunk is not BIN").toBe(0x004e4942);
  const binLen = buf.readUInt32LE(binHeader);
  const bin = buf.subarray(binHeader + 8, binHeader + 8 + binLen);
  return { gltf, bin };
}

/**
 * Raw scalars of an accessor, honouring interleaving.
 *
 * `byteStride` is per element, and the plain copies are interleaved (POSITION
 * and NORMAL share one 24-byte view). Reading them as tightly packed returns
 * normals as positions without any error.
 */
function read(gltf: Gltf, bin: Buffer, index: number): number[] {
  const acc = gltf.accessors[index];
  const view = gltf.bufferViews[acc.bufferView];
  const width = { SCALAR: 1, VEC2: 2, VEC3: 3, VEC4: 4 }[acc.type];
  expect(width, `unhandled accessor type ${acc.type}`).toBeDefined();
  const size = { 5123: 2, 5125: 4, 5126: 4 }[acc.componentType as 5123 | 5125 | 5126];
  expect(size, `unhandled component type ${acc.componentType}`).toBeDefined();
  const stride = view.byteStride ?? width! * size;
  const base = (view.byteOffset ?? 0) + (acc.byteOffset ?? 0);
  const out: number[] = [];
  for (let e = 0; e < acc.count; e++) {
    for (let j = 0; j < width!; j++) {
      const at = base + e * stride + j * size;
      out.push(
        acc.componentType === 5126
          ? bin.readFloatLE(at)
          : acc.componentType === 5125
            ? bin.readUInt32LE(at)
            : bin.readUInt16LE(at),
      );
    }
  }
  return out;
}

/** One triangle's three vertex normals. Positions come back in `verts`. */
type Tri = [number, number, number][];

/** Every triangle's normals, plus every vertex position with node transforms applied. */
function triangles(file: string): { tris: Tri[]; verts: [number, number, number][] } {
  const { gltf, bin } = readGlb(file);
  const tris: Tri[] = [];
  const verts: [number, number, number][] = [];
  for (const node of gltf.nodes) {
    if (node.mesh === undefined) continue;
    const q = node.rotation ?? [0, 0, 0, 1];
    // A tipped node would skew every measurement below, so assert it.
    expect(
      Math.abs(q[0]) + Math.abs(q[1]) + Math.abs(q[2]),
      `${node.name ?? "?"} is rotated`,
    ).toBeLessThan(1e-6);
    const t = node.translation ?? [0, 0, 0];
    const s = node.scale ?? [1, 1, 1];
    for (const prim of gltf.meshes[node.mesh].primitives) {
      const pos = read(gltf, bin, prim.attributes.POSITION);
      const nor = read(gltf, bin, prim.attributes.NORMAL);
      const idx =
        prim.indices === undefined
          ? [...Array(pos.length / 3).keys()]
          : read(gltf, bin, prim.indices);
      const at = (i: number): [number, number, number] => [
        pos[i * 3] * s[0] + t[0],
        pos[i * 3 + 1] * s[1] + t[1],
        pos[i * 3 + 2] * s[2] + t[2],
      ];
      for (let i = 0; i < pos.length / 3; i++) verts.push(at(i));
      for (let i = 0; i < idx.length; i += 3) {
        tris.push(
          [idx[i], idx[i + 1], idx[i + 2]].map(
            (v) => [nor[v * 3], nor[v * 3 + 1], nor[v * 3 + 2]] as [number, number, number],
          ),
        );
      }
    }
  }
  expect(tris.length, `${file} parsed to no triangles`).toBeGreaterThan(0);
  return { tris, verts };
}

/**
 * Every vertex of the nodes named exactly `names`, with node transforms applied.
 *
 * Per vertex, not per bounding box: an accessor's min/max pairs the lowest x
 * with the lowest z, a corner an octagonal platform does not have, which
 * understates clearance by half a unit.
 */
function nodeVerts(file: string, names: string[]): [number, number, number][] {
  const { gltf, bin } = readGlb(file);
  const wanted = new Set(names);
  const out: [number, number, number][] = [];
  let found = 0;
  for (const node of gltf.nodes) {
    if (node.mesh === undefined) continue;
    const name = node.name ?? gltf.meshes[node.mesh].name ?? "";
    if (!wanted.has(name)) continue;
    found++;
    const t = node.translation ?? [0, 0, 0];
    const s = node.scale ?? [1, 1, 1];
    for (const prim of gltf.meshes[node.mesh].primitives) {
      const pos = read(gltf, bin, prim.attributes.POSITION);
      for (let i = 0; i < pos.length / 3; i++)
        out.push([
          pos[i * 3] * s[0] + t[0],
          pos[i * 3 + 1] * s[1] + t[1],
          pos[i * 3 + 2] * s[2] + t[2],
        ]);
    }
  }
  expect(found, `none of ${names.join(", ")} are in ${file}`).toBe(names.length);
  return out;
}

/** The bounds of every node named `prefix*`, from the accessors' own min/max. */
function span(file: string, prefix: string): { lo: number[]; hi: number[] } {
  const { gltf } = readGlb(file);
  const lo = [Infinity, Infinity, Infinity];
  const hi = [-Infinity, -Infinity, -Infinity];
  let found = 0;
  for (const node of gltf.nodes) {
    if (node.mesh === undefined) continue;
    // The mesh's name where the node has none: a slab comes back as an unnamed
    // node wrapping a mesh called `Hex_<Terrain>`.
    const name = node.name ?? gltf.meshes[node.mesh].name;
    if (typeof name !== "string" || !name.startsWith(prefix)) continue;
    found++;
    const t = node.translation ?? [0, 0, 0];
    const s = node.scale ?? [1, 1, 1];
    for (const prim of gltf.meshes[node.mesh].primitives) {
      const acc = gltf.accessors[prim.attributes.POSITION];
      for (let i = 0; i < 3; i++) {
        lo[i] = Math.min(lo[i], acc.min![i] * s[i] + t[i], acc.max![i] * s[i] + t[i]);
        hi[i] = Math.max(hi[i], acc.min![i] * s[i] + t[i], acc.max![i] * s[i] + t[i]);
      }
    }
  }
  expect(found, `${prefix}: no geometry found in ${file}`).toBeGreaterThan(0);
  return { lo, hi };
}

test("the castle slab matches the land hex size", () => {
  // A water tile is authored a full lattice cell wide (circumradius 3.1443, top
  // at 0.1596) and scaled to fill it at load; a land tile is authored at 3.0
  // with its top at 0.22 and keeps its size, leaving the perimeter for roads and
  // buildings. Measured against both reference tiles.
  const castle = span(CASTLE, "Hex_Castle");
  const desert = span("tiles/none.glb", "Hex_Desert");
  const ocean = span("tiles/sea.glb", "Hex_Ocean");

  expect(castle.hi[2] - castle.lo[2], "circumradius").toBeCloseTo(desert.hi[2] - desert.lo[2], 4);
  expect(castle.hi[1], "top face").toBeCloseTo(desert.hi[1], 4);
  expect(castle.lo[1], "underside").toBeCloseTo(desert.lo[1], 4);
  expect(castle.hi[2] - castle.lo[2]).not.toBeCloseTo(ocean.hi[2] - ocean.lo[2], 2);

  expect(tileScale(CASTLE_TILE)).toBe(1);
  expect(tileScale("sea")).toBeGreaterThan(1);
});

test("nothing on the castle crosses into the gutter", () => {
  // The gutter holds roads, settlements and paths, so a tile must not reach
  // past its circumradius. The castle is a building pushed off centre, so it is
  // the most likely to.
  const { verts } = triangles(CASTLE);
  let worst = 0;
  for (const [x, , z] of verts) worst = Math.max(worst, Math.hypot(x, z));
  expect(worst, "art reach").toBeLessThanOrEqual(3.0 + 1e-3);
  // And it fills its hexagon rather than sitting small in the middle.
  expect(worst).toBeGreaterThan(2.9);
});

test("the castle keeps the chip socket clear", () => {
  // Every land tile mounts its chip at (0, +1.5) in Blender, (0, 0.26, -1.5)
  // in glTF, and nothing may rise above the chip's underside within 1.05 of it.
  // No chip lands on a castle, but the socket remains (a marker may use it).
  //
  // A curtain wall centred on the tile would cross this disc, so the castle is
  // pushed south; this measures the resulting geometry.
  const socket = TILES[CASTLE_TILE].socket;
  expect(socket, "castle socket").not.toBeNull();
  const [sx, sy, sz] = socket!;
  expect([sx, sy, sz]).toEqual([0, 0.26, -1.5]);

  const { verts } = triangles(CASTLE);
  const CHIP_UNDERSIDE = 0.25;
  const KEEP_CLEAR = 1.05;
  let nearest = Infinity;
  for (const [x, y, z] of verts) {
    if (y <= CHIP_UNDERSIDE) continue;
    nearest = Math.min(nearest, Math.hypot(x - sx, z - sz));
  }
  expect(nearest, "nearest geometry to the chip socket").toBeGreaterThan(KEEP_CLEAR);
  // The nearest thing is a sheep from the pasture scatter, at 1.075. The
  // generator moves conflicting props by the shortest clearing hop
  // (`resolve_clusters`), and the socket disc is one of the things it clears,
  // so this shows that pass ran. The compound itself sits further back:
  let nearestBuilt = Infinity;
  for (const [x, y, z] of nodeVerts(CASTLE, [
    "Castle_keep",
    "Castle_towers",
    "Castle_curtain",
    "Castle_gate",
  ])) {
    if (y <= CHIP_UNDERSIDE) continue;
    nearestBuilt = Math.min(nearestBuilt, Math.hypot(x - sx, z - sz));
  }
  // The walls and towers stay past 1.4 (the motte is part of the ground
  // lattice now). Both clear the 1.05 disc.
  expect(nearestBuilt, "compound clearance").toBeGreaterThan(1.25);
});

test("the castle stays under the tile's prop ceiling", () => {
  // 2.30 is the ceiling, just above `Mountains_massif` at 2.290. From 56
  // degrees of elevation height hides the tiles behind, so a keep may not
  // tower over the mountains.
  const { verts } = triangles(CASTLE);
  const top = Math.max(...verts.map(([, y]) => y));
  expect(top).toBeLessThanOrEqual(2.3 + 1e-3);
  // A tower, not a bump: the keep must clear the settlements on this tile's
  // vertices, which top out around 0.65.
  expect(top).toBeGreaterThan(1.8);
});

test("every polygon on the castle is flat-shaded", () => {
  // Flat shading: a smooth-shaded face ships with three different normals and
  // reads as a soft blob among faceted tiles.
  const { tris } = triangles(CASTLE);
  let smooth = 0;
  for (const n of tris) {
    const [a] = n;
    const same = n.every(
      (v) => Math.abs(v[0] - a[0]) + Math.abs(v[1] - a[1]) + Math.abs(v[2] - a[2]) < 1e-4,
    );
    if (!same) smooth++;
  }
  expect(smooth, `${smooth} of ${tris.length} triangles are smooth-shaded`).toBe(0);
});

test("the castle stays within the tile triangle budget", () => {
  // Budget: 3643 triangles, the heaviest tile budget. Too many and one hex
  // costs what the board costs; too few and the ground is a flat plate.
  const HEAVIEST_TILE = 3643;
  const { tris } = triangles(CASTLE);
  expect(tris.length).toBeGreaterThan(1000);
  expect(tris.length).toBeLessThanOrEqual(HEAVIEST_TILE);
});

test("the castle border matches the pasture border", () => {
  // `art/README.md` says `Castle_rim` is `Pasture_rim`, appended and renamed.
  // The rim only renders as a lip if the slab under it and the ground over it
  // sit at 0.220, so all three surfaces are compared against the pasture tile.
  //
  // The ground matches the pasture in plan but not height: the motte is folded
  // into it, so its ceiling is the motte's and its floor the pond's bed.
  const pairs: [string, string, number[]][] = [
    ["Castle_rim", "Pasture_rim", [0, 1, 2]],
    ["Castle_ground", "Pasture_ground", [0, 2]],
    ["Hex_Castle", "Hex_Pasture", [0, 1, 2]],
  ];
  for (const [mine, theirs, axes] of pairs) {
    const a = span(CASTLE, mine);
    const b = span("tiles/sheep.glb", theirs);
    for (const i of axes) {
      expect(a.lo[i], `${mine} is not ${theirs}: axis ${i} floor`).toBeCloseTo(b.lo[i], 4);
      expect(a.hi[i], `${mine} is not ${theirs}: axis ${i} ceiling`).toBeCloseTo(b.hi[i], 4);
    }
  }
  // Nowhere under the slab's top, which would show the slab through it.
  expect(span(CASTLE, "Castle_ground").lo[1]).toBeGreaterThan(span(CASTLE, "Hex_Castle").hi[1]);
  // `Mat_Pasture_mud` is the band at the rim's cutbank that draws the tile
  // outline now that the sunk slab casts none, so the castle needs it too.
  const names = (readGlb(CASTLE).gltf.materials ?? []).map((m) => m.name ?? "");
  expect(names, "castle materials").toContain("Mat_Pasture_mud");
});

test("the castle shares the pasture turf materials", () => {
  // The castle is built in `art/hexes/pasture.blend` and keeps its turf
  // lattice, rim, barn, field wall, hedge, pond and flock, so it matches the
  // neighbouring pasture. `Mat_Pasture_grass_mid` on a castle hex is
  // intentional (`art/hexes/port.blend` likewise ships Mat_Pasture_wood and
  // Mat_Fields_sheaf).
  //
  // The rule: the keep's stone, roof, earth and banner are new, and every other
  // material is one another shipped tile already wears.
  const { gltf } = readGlb(CASTLE);
  const names = (gltf.materials ?? []).map((m) => m.name ?? "");
  expect(names.length).toBeGreaterThan(5);

  const pastureNames = new Set(
    (readGlb("tiles/sheep.glb").gltf.materials ?? []).map((m) => m.name ?? ""),
  );
  const forestNames = new Set(
    (readGlb("tiles/wood.glb").gltf.materials ?? []).map((m) => m.name ?? ""),
  );
  for (const name of names) {
    if (name.startsWith("Mat_Castle_")) continue;
    expect(
      pastureNames.has(name) || forestNames.has(name),
      `${name} is neither the castle's own nor a material the pasture or forest ships`,
    ).toBe(true);
  }
  // The turf itself, named, so re-deriving the ground fails here.
  for (const green of ["Mat_Pasture_grass_lit", "Mat_Pasture_grass_mid", "Mat_Pasture_grass_dk"])
    expect(names, `the castle stopped sharing the pasture's ${green}`).toContain(green);
  // And the keep is the castle's own, in warm stone and a saturated roof.
  for (const own of ["Mat_Castle_stone", "Mat_Castle_roof", "Mat_Castle_banner"])
    expect(names).toContain(own);

  // palette.json overrides by material name, so a material without an entry
  // cannot be restyled. `palette.test.ts` checks the reverse across the set.
  const palette = JSON.parse(
    readFileSync(join(__dirname, "..", "..", "..", "public", "models", "palette.json"), "utf8"),
  ) as Record<string, { color: number[] }>;
  for (const name of names) expect(palette[name], `palette missing ${name}`).toBeDefined();
});
