// GENERATED by tools/blender/export_assets.py -- do not edit.
// Re-run `make export-assets` after changing anything under art/.
import { COMPOSED_TILES } from "./manifest.composed.generated";

export interface TileEntry {
  resource: string;
  file: string;
  socket: [number, number, number] | null;
  /**
   * Standing slots on the tile, in slot order and in the socket's frame
   * (`LairSlot_<n>` / `FarmSlot_<n>` empties, see SLOT_PREFIXES in the
   * exporter). Absent on every tile that has none.
   */
  slots?: [number, number, number][];
}

export interface ChipEntry {
  number: number;
  variants: number;
}

/** Hex circumradius in blend units. */
export const HEX_SIZE = 3.0;

/** The tiles exported from a blend under art/hexes/. */
const EXPORTED_TILES: Record<string, TileEntry> = {
  "brick": {
    "resource": "brick",
    "file": "tiles/brick.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "castle": {
    "resource": "castle",
    "file": "tiles/castle.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "generic": {
    "resource": "generic",
    "file": "tiles/generic.glb",
    "socket": [
      0.0,
      0.26,
      -0.0
    ]
  },
  "gold": {
    "resource": "gold",
    "file": "tiles/gold.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "goldfield": {
    "resource": "goldfield",
    "file": "tiles/goldfield.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ],
    "slots": [
      [
        -1.2,
        0.296,
        -1.25
      ],
      [
        -1.68,
        0.615,
        -1.25
      ],
      [
        -2.16,
        0.513,
        -1.25
      ],
      [
        1.2,
        0.293,
        -1.3
      ],
      [
        1.68,
        0.369,
        -1.3
      ],
      [
        2.16,
        0.245,
        -1.3
      ],
      [
        -1.44,
        0.289,
        -1.8
      ],
      [
        1.44,
        0.291,
        -1.8
      ]
    ]
  },
  "lake": {
    "resource": "lake",
    "file": "tiles/lake.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "none": {
    "resource": "none",
    "file": "tiles/none.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "oasis": {
    "resource": "oasis",
    "file": "tiles/oasis.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "ore": {
    "resource": "ore",
    "file": "tiles/ore.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_hills_e_nw": {
    "resource": "river_hills_e_nw",
    "file": "tiles/river_hills_e_nw.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_hills_e_sw": {
    "resource": "river_hills_e_sw",
    "file": "tiles/river_hills_e_sw.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_hills_e_w_a": {
    "resource": "river_hills_e_w_a",
    "file": "tiles/river_hills_e_w_a.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_hills_e_w_b": {
    "resource": "river_hills_e_w_b",
    "file": "tiles/river_hills_e_w_b.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_hills_ne_se": {
    "resource": "river_hills_ne_se",
    "file": "tiles/river_hills_ne_se.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_hills_ne_sw": {
    "resource": "river_hills_ne_sw",
    "file": "tiles/river_hills_ne_sw.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_hills_ne_w": {
    "resource": "river_hills_ne_w",
    "file": "tiles/river_hills_ne_w.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_hills_nw_se": {
    "resource": "river_hills_nw_se",
    "file": "tiles/river_hills_nw_se.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_hills_nw_sw": {
    "resource": "river_hills_nw_sw",
    "file": "tiles/river_hills_nw_sw.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_hills_w_se": {
    "resource": "river_hills_w_se",
    "file": "tiles/river_hills_w_se.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_mountains_e_nw": {
    "resource": "river_mountains_e_nw",
    "file": "tiles/river_mountains_e_nw.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_mountains_e_sw": {
    "resource": "river_mountains_e_sw",
    "file": "tiles/river_mountains_e_sw.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_mountains_e_w_a": {
    "resource": "river_mountains_e_w_a",
    "file": "tiles/river_mountains_e_w_a.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_mountains_e_w_b": {
    "resource": "river_mountains_e_w_b",
    "file": "tiles/river_mountains_e_w_b.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_mountains_ne_se": {
    "resource": "river_mountains_ne_se",
    "file": "tiles/river_mountains_ne_se.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_mountains_ne_sw": {
    "resource": "river_mountains_ne_sw",
    "file": "tiles/river_mountains_ne_sw.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_mountains_ne_w": {
    "resource": "river_mountains_ne_w",
    "file": "tiles/river_mountains_ne_w.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_mountains_nw_se": {
    "resource": "river_mountains_nw_se",
    "file": "tiles/river_mountains_nw_se.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_mountains_nw_sw": {
    "resource": "river_mountains_nw_sw",
    "file": "tiles/river_mountains_nw_sw.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_mountains_src_e": {
    "resource": "river_mountains_src_e",
    "file": "tiles/river_mountains_src_e.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_mountains_src_ne": {
    "resource": "river_mountains_src_ne",
    "file": "tiles/river_mountains_src_ne.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_mountains_src_nw": {
    "resource": "river_mountains_src_nw",
    "file": "tiles/river_mountains_src_nw.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_mountains_src_se": {
    "resource": "river_mountains_src_se",
    "file": "tiles/river_mountains_src_se.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_mountains_src_sw": {
    "resource": "river_mountains_src_sw",
    "file": "tiles/river_mountains_src_sw.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_mountains_src_w": {
    "resource": "river_mountains_src_w",
    "file": "tiles/river_mountains_src_w.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_mountains_w_se": {
    "resource": "river_mountains_w_se",
    "file": "tiles/river_mountains_w_se.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_pasture_e_nw": {
    "resource": "river_pasture_e_nw",
    "file": "tiles/river_pasture_e_nw.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_pasture_e_sw": {
    "resource": "river_pasture_e_sw",
    "file": "tiles/river_pasture_e_sw.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_pasture_e_w_a": {
    "resource": "river_pasture_e_w_a",
    "file": "tiles/river_pasture_e_w_a.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_pasture_e_w_b": {
    "resource": "river_pasture_e_w_b",
    "file": "tiles/river_pasture_e_w_b.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_pasture_ne_se": {
    "resource": "river_pasture_ne_se",
    "file": "tiles/river_pasture_ne_se.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_pasture_ne_sw": {
    "resource": "river_pasture_ne_sw",
    "file": "tiles/river_pasture_ne_sw.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_pasture_ne_w": {
    "resource": "river_pasture_ne_w",
    "file": "tiles/river_pasture_ne_w.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_pasture_nw_se": {
    "resource": "river_pasture_nw_se",
    "file": "tiles/river_pasture_nw_se.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_pasture_nw_sw": {
    "resource": "river_pasture_nw_sw",
    "file": "tiles/river_pasture_nw_sw.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_pasture_w_se": {
    "resource": "river_pasture_w_se",
    "file": "tiles/river_pasture_w_se.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_swamp_e_nw": {
    "resource": "river_swamp_e_nw",
    "file": "tiles/river_swamp_e_nw.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_swamp_e_sw": {
    "resource": "river_swamp_e_sw",
    "file": "tiles/river_swamp_e_sw.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_swamp_e_w_a": {
    "resource": "river_swamp_e_w_a",
    "file": "tiles/river_swamp_e_w_a.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_swamp_e_w_b": {
    "resource": "river_swamp_e_w_b",
    "file": "tiles/river_swamp_e_w_b.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_swamp_ne_se": {
    "resource": "river_swamp_ne_se",
    "file": "tiles/river_swamp_ne_se.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_swamp_ne_sw": {
    "resource": "river_swamp_ne_sw",
    "file": "tiles/river_swamp_ne_sw.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_swamp_ne_w": {
    "resource": "river_swamp_ne_w",
    "file": "tiles/river_swamp_ne_w.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_swamp_nw_se": {
    "resource": "river_swamp_nw_se",
    "file": "tiles/river_swamp_nw_se.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_swamp_nw_sw": {
    "resource": "river_swamp_nw_sw",
    "file": "tiles/river_swamp_nw_sw.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "river_swamp_w_se": {
    "resource": "river_swamp_w_se",
    "file": "tiles/river_swamp_w_se.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "sea": {
    "resource": "sea",
    "file": "tiles/sea.glb",
    "socket": null
  },
  "sea_council": {
    "resource": "sea_council",
    "file": "tiles/sea_council.glb",
    "socket": null
  },
  "sea_port": {
    "resource": "sea_port",
    "file": "tiles/sea_port.glb",
    "socket": null
  },
  "sea_shoal": {
    "resource": "sea_shoal",
    "file": "tiles/sea_shoal.glb",
    "socket": null
  },
  "sheep": {
    "resource": "sheep",
    "file": "tiles/sheep.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "spice": {
    "resource": "spice",
    "file": "tiles/spice.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ],
    "slots": [
      [
        -0.9,
        0.233,
        -1.2
      ],
      [
        -0.45,
        0.228,
        -1.2
      ],
      [
        0.0,
        0.231,
        -1.2
      ],
      [
        0.45,
        0.232,
        -1.2
      ],
      [
        0.9,
        0.231,
        -1.2
      ],
      [
        -0.9,
        0.233,
        -1.75
      ],
      [
        -0.45,
        0.231,
        -1.75
      ],
      [
        0.0,
        0.232,
        -1.75
      ],
      [
        0.45,
        0.228,
        -1.75
      ],
      [
        0.9,
        0.231,
        -1.75
      ]
    ]
  },
  "swamp": {
    "resource": "swamp",
    "file": "tiles/swamp.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "wheat": {
    "resource": "wheat",
    "file": "tiles/wheat.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  },
  "wood": {
    "resource": "wood",
    "file": "tiles/wood.glb",
    "socket": [
      0.0,
      0.26,
      -1.5
    ]
  }
};

/**
 * Every tile: the exported ones above, and the recipe-built ones
 * (`make compose-tiles`, art/recipes/), which the composer writes into their
 * own generated file so that neither generator writes the other's.
 */
export const TILES: Record<string, TileEntry> = { ...EXPORTED_TILES, ...COMPOSED_TILES };

export const CHIPS: ChipEntry[] = [
  {
    "number": 2,
    "variants": 1
  },
  {
    "number": 3,
    "variants": 2
  },
  {
    "number": 4,
    "variants": 2
  },
  {
    "number": 5,
    "variants": 2
  },
  {
    "number": 6,
    "variants": 2
  },
  {
    "number": 8,
    "variants": 2
  },
  {
    "number": 9,
    "variants": 2
  },
  {
    "number": 10,
    "variants": 2
  },
  {
    "number": 11,
    "variants": 2
  },
  {
    "number": 12,
    "variants": 1
  }
];

/** Material names the runtime recolors per seat. */
export const TINT_SLOTS = ["Seat_Body", "Seat_Detail", "Seat_Shade"] as const;

/** Engine resources with no art; render the mapped tile instead. */
export const RESOURCE_FALLBACK: Record<string, string> = {
  "fog": "sea"
};
