// GENERATED by frontend/scripts/compose-tiles.ts -- do not edit.
// Re-run `make compose-tiles` after changing anything under art/recipes/.
//
// The recipe-built tiles, spread into `TILES` by manifest.generated.ts.
import type { TileEntry } from "./manifest.generated";

export const COMPOSED_TILES: Record<string, TileEntry> = {
  "river_fields_e_nw": {
    "resource": "river_fields_e_nw",
    "file": "tiles/river_fields_e_nw.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "river_fields_e_sw": {
    "resource": "river_fields_e_sw",
    "file": "tiles/river_fields_e_sw.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "river_fields_e_w_a": {
    "resource": "river_fields_e_w_a",
    "file": "tiles/river_fields_e_w_a.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "river_fields_e_w_b": {
    "resource": "river_fields_e_w_b",
    "file": "tiles/river_fields_e_w_b.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "river_fields_ne_se": {
    "resource": "river_fields_ne_se",
    "file": "tiles/river_fields_ne_se.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "river_fields_ne_sw": {
    "resource": "river_fields_ne_sw",
    "file": "tiles/river_fields_ne_sw.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "river_fields_ne_w": {
    "resource": "river_fields_ne_w",
    "file": "tiles/river_fields_ne_w.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "river_fields_nw_se": {
    "resource": "river_fields_nw_se",
    "file": "tiles/river_fields_nw_se.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "river_fields_nw_sw": {
    "resource": "river_fields_nw_sw",
    "file": "tiles/river_fields_nw_sw.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "river_fields_w_se": {
    "resource": "river_fields_w_se",
    "file": "tiles/river_fields_w_se.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "river_forest_e_nw": {
    "resource": "river_forest_e_nw",
    "file": "tiles/river_forest_e_nw.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "river_forest_e_sw": {
    "resource": "river_forest_e_sw",
    "file": "tiles/river_forest_e_sw.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "river_forest_e_w_a": {
    "resource": "river_forest_e_w_a",
    "file": "tiles/river_forest_e_w_a.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "river_forest_e_w_b": {
    "resource": "river_forest_e_w_b",
    "file": "tiles/river_forest_e_w_b.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "river_forest_ne_se": {
    "resource": "river_forest_ne_se",
    "file": "tiles/river_forest_ne_se.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "river_forest_ne_sw": {
    "resource": "river_forest_ne_sw",
    "file": "tiles/river_forest_ne_sw.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "river_forest_ne_w": {
    "resource": "river_forest_ne_w",
    "file": "tiles/river_forest_ne_w.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "river_forest_nw_se": {
    "resource": "river_forest_nw_se",
    "file": "tiles/river_forest_nw_se.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "river_forest_nw_sw": {
    "resource": "river_forest_nw_sw",
    "file": "tiles/river_forest_nw_sw.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "river_forest_w_se": {
    "resource": "river_forest_w_se",
    "file": "tiles/river_forest_w_se.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_desert_e": {
    "resource": "trade_desert_e",
    "file": "tiles/trade_desert_e.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_desert_ne": {
    "resource": "trade_desert_ne",
    "file": "tiles/trade_desert_ne.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_desert_nw": {
    "resource": "trade_desert_nw",
    "file": "tiles/trade_desert_nw.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_desert_se": {
    "resource": "trade_desert_se",
    "file": "tiles/trade_desert_se.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_desert_sw": {
    "resource": "trade_desert_sw",
    "file": "tiles/trade_desert_sw.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_desert_w": {
    "resource": "trade_desert_w",
    "file": "tiles/trade_desert_w.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_fields_e": {
    "resource": "trade_fields_e",
    "file": "tiles/trade_fields_e.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_fields_ne": {
    "resource": "trade_fields_ne",
    "file": "tiles/trade_fields_ne.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_fields_nw": {
    "resource": "trade_fields_nw",
    "file": "tiles/trade_fields_nw.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_fields_se": {
    "resource": "trade_fields_se",
    "file": "tiles/trade_fields_se.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_fields_sw": {
    "resource": "trade_fields_sw",
    "file": "tiles/trade_fields_sw.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_fields_w": {
    "resource": "trade_fields_w",
    "file": "tiles/trade_fields_w.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_forest_e": {
    "resource": "trade_forest_e",
    "file": "tiles/trade_forest_e.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_forest_ne": {
    "resource": "trade_forest_ne",
    "file": "tiles/trade_forest_ne.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_forest_nw": {
    "resource": "trade_forest_nw",
    "file": "tiles/trade_forest_nw.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_forest_se": {
    "resource": "trade_forest_se",
    "file": "tiles/trade_forest_se.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_forest_sw": {
    "resource": "trade_forest_sw",
    "file": "tiles/trade_forest_sw.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_forest_w": {
    "resource": "trade_forest_w",
    "file": "tiles/trade_forest_w.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_hills_e": {
    "resource": "trade_hills_e",
    "file": "tiles/trade_hills_e.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_hills_ne": {
    "resource": "trade_hills_ne",
    "file": "tiles/trade_hills_ne.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_hills_nw": {
    "resource": "trade_hills_nw",
    "file": "tiles/trade_hills_nw.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_hills_se": {
    "resource": "trade_hills_se",
    "file": "tiles/trade_hills_se.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_hills_sw": {
    "resource": "trade_hills_sw",
    "file": "tiles/trade_hills_sw.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_hills_w": {
    "resource": "trade_hills_w",
    "file": "tiles/trade_hills_w.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_lake_e": {
    "resource": "trade_lake_e",
    "file": "tiles/trade_lake_e.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_lake_ne": {
    "resource": "trade_lake_ne",
    "file": "tiles/trade_lake_ne.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_lake_nw": {
    "resource": "trade_lake_nw",
    "file": "tiles/trade_lake_nw.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_lake_se": {
    "resource": "trade_lake_se",
    "file": "tiles/trade_lake_se.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_lake_sw": {
    "resource": "trade_lake_sw",
    "file": "tiles/trade_lake_sw.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_lake_w": {
    "resource": "trade_lake_w",
    "file": "tiles/trade_lake_w.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_mountains_e": {
    "resource": "trade_mountains_e",
    "file": "tiles/trade_mountains_e.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_mountains_ne": {
    "resource": "trade_mountains_ne",
    "file": "tiles/trade_mountains_ne.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_mountains_nw": {
    "resource": "trade_mountains_nw",
    "file": "tiles/trade_mountains_nw.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_mountains_se": {
    "resource": "trade_mountains_se",
    "file": "tiles/trade_mountains_se.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_mountains_sw": {
    "resource": "trade_mountains_sw",
    "file": "tiles/trade_mountains_sw.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_mountains_w": {
    "resource": "trade_mountains_w",
    "file": "tiles/trade_mountains_w.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_pasture_e": {
    "resource": "trade_pasture_e",
    "file": "tiles/trade_pasture_e.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_pasture_ne": {
    "resource": "trade_pasture_ne",
    "file": "tiles/trade_pasture_ne.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_pasture_nw": {
    "resource": "trade_pasture_nw",
    "file": "tiles/trade_pasture_nw.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_pasture_se": {
    "resource": "trade_pasture_se",
    "file": "tiles/trade_pasture_se.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_pasture_sw": {
    "resource": "trade_pasture_sw",
    "file": "tiles/trade_pasture_sw.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_pasture_w": {
    "resource": "trade_pasture_w",
    "file": "tiles/trade_pasture_w.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_swamp_e": {
    "resource": "trade_swamp_e",
    "file": "tiles/trade_swamp_e.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_swamp_ne": {
    "resource": "trade_swamp_ne",
    "file": "tiles/trade_swamp_ne.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_swamp_nw": {
    "resource": "trade_swamp_nw",
    "file": "tiles/trade_swamp_nw.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_swamp_se": {
    "resource": "trade_swamp_se",
    "file": "tiles/trade_swamp_se.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_swamp_sw": {
    "resource": "trade_swamp_sw",
    "file": "tiles/trade_swamp_sw.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  },
  "trade_swamp_w": {
    "resource": "trade_swamp_w",
    "file": "tiles/trade_swamp_w.glb",
    "socket": [
      0,
      0.26,
      -1.5
    ]
  }
};
