import { test, expect } from "vitest";
import * as THREE from "three";
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import {
  applyPalette,
  currentEmissiveBoost,
  glowingMaterialCount,
  setEmissiveBoost,
  type Palette,
} from "./palette";
import { TINT_SLOTS } from "./manifest.generated";

const SHIPPED_PALETTE_PATH = join(__dirname, "..", "..", "..", "public", "models", "palette.json");
const SHIPPED_MODELS = join(__dirname, "..", "..", "..", "public", "models");

/** Every .glb under public/models, path relative to that directory. */
const ALL_SHIPPED_GLBS = (function walk(dir: string, prefix = ""): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((e) =>
    e.isDirectory()
      ? walk(join(dir, e.name), `${prefix}${e.name}/`)
      : e.name.endsWith(".glb")
        ? [`${prefix}${e.name}`]
        : [],
  );
})(SHIPPED_MODELS);

/**
 * The material names inside a shipped .glb, read straight from the JSON chunk
 * (GLTFLoader needs a browser and the meshopt decoder). Compression leaves
 * material names alone; loader.test.ts pins that.
 */
function materialsIn(file: string): string[] {
  const buf = readFileSync(join(SHIPPED_MODELS, file));
  expect(buf.readUInt32LE(0), `${file} is not a GLB`).toBe(0x46546c67);
  const jsonLength = buf.readUInt32LE(12);
  const doc = JSON.parse(buf.subarray(20, 20 + jsonLength).toString("utf8")) as {
    materials?: { name?: string }[];
  };
  return (doc.materials ?? []).flatMap((m) => (m.name ? [m.name] : []));
}

const palette: Palette = {
  Mat_Desert: { color: [0.85, 0.618, 0.306], roughness: 0.85, metalness: 0 },
};

test("a palette material takes its color, roughness and metalness", () => {
  const m = new THREE.MeshStandardMaterial({ name: "Mat_Desert" });
  expect(applyPalette(m, palette)).toBe(true);
  expect(m.roughness).toBeCloseTo(0.85, 4);
  expect(m.metalness).toBeCloseTo(0, 4);
  // palette.json stores linear values straight from Blender's Base Color.
  expect(m.color.r).toBeCloseTo(0.85, 4);
  expect(m.color.g).toBeCloseTo(0.618, 4);
  expect(m.color.b).toBeCloseTo(0.306, 4);
});

test("a material absent from the palette is left alone", () => {
  const m = new THREE.MeshStandardMaterial({ name: "Mat_Nonexistent" });
  const before = m.color.getHex();
  expect(applyPalette(m, palette)).toBe(false);
  expect(m.color.getHex()).toBe(before);
});

test("an unnamed material is left alone rather than throwing", () => {
  const m = new THREE.MeshStandardMaterial();
  expect(applyPalette(m, palette)).toBe(false);
});

test("the shipped palette covers the seat tint slots", () => {
  // A missing Seat_Body would render every player's pieces in the glTF default
  // colour. Reads the shipped file and takes the slots from TINT_SLOTS
  // (generated by tools/blender/export_assets.py), so a new seat material
  // fails here until palette.json has a tone for it. loader.test.ts names the
  // current three by hand as a second check.
  const shipped = JSON.parse(readFileSync(SHIPPED_PALETTE_PATH, "utf8")) as Palette;
  const missing = TINT_SLOTS.filter((slot) => !shipped[slot]);
  expect(missing, `palette.json has no tone for ${missing.join(", ")}`).toEqual([]);
  for (const slot of TINT_SLOTS) {
    expect(shipped[slot].color, `${slot} must carry an RGB triple`).toHaveLength(3);
  }
});

test("the metropolises are limestone towers with muted discipline caps", () => {
  // Metropolis towers: a full-colour tower on a seat-tinted base read as a
  // second player on the owner's base. So every tower body is the wall's warm
  // limestone and each discipline keeps a muted cap (trade a saffron roof,
  // politics a cream standard on a dark pole, science a verdigris dome) while
  // the seat colour stays on the base. Material names are unchanged
  // (loader.test.ts pins them); only palette.json moved.
  const shipped = JSON.parse(readFileSync(SHIPPED_PALETTE_PATH, "utf8")) as Palette;
  const c = (n: string) => {
    expect(shipped[n], `${n} is missing from palette.json`).toBeDefined();
    return shipped[n].color;
  };
  const limestone = c("Mat_Castle_stone_lt");
  for (const body of [
    "Mat_Metro_trade_hall",
    "Mat_Metro_politics_keep",
    "Mat_Metro_science_drum",
  ]) {
    expect(c(body), `${body} is the wall's limestone`).toEqual(limestone);
  }
  const chroma = ([r, g, b]: [number, number, number]) => Math.max(r, g, b) - Math.min(r, g, b);
  // Muted: no cap is as saturated as a seat colour.
  for (const cap of [
    "Mat_Metro_trade_roof",
    "Mat_Metro_science_dome",
    "Mat_Metro_politics_banner",
  ]) {
    expect(chroma(c(cap)), `${cap} is a muted cap`).toBeLessThan(0.7);
  }
  const [rr, rg, rb] = c("Mat_Metro_trade_roof");
  expect(rr > rg && rg > rb, "trade's roof is saffron").toBe(true);
  const [dr, dg, db] = c("Mat_Metro_science_dome");
  expect(dg > dr && dg > db, "science's dome is verdigris").toBe(true);
  expect(c("Mat_Metro_politics_banner")).toEqual(c("Mat_Castle_banner"));
  // Three different caps, so the disciplines are still told apart by colour
  // as well as by silhouette.
  const caps = ["Mat_Metro_trade_roof", "Mat_Metro_science_dome", "Mat_Metro_politics_banner"].map(
    (n) => c(n).join(","),
  );
  expect(new Set(caps).size).toBe(3);
});

test("a self-lit entry makes the material emissive", () => {
  // Self-lit materials, which the `vibrant` and `mist` styles use: a lit window
  // must be brighter than its own wall from every angle, which no light rig
  // can fake.
  const m = new THREE.MeshStandardMaterial({ name: "Mat_Window" });
  setEmissiveBoost(1);
  expect(
    applyPalette(m, {
      Mat_Window: {
        color: [0.1, 0.1, 0.1],
        roughness: 0.5,
        metalness: 0,
        emissive: [1, 0.7, 0.3],
        emissiveIntensity: 2,
      },
    }),
  ).toBe(true);
  expect(m.emissive.r).toBeCloseTo(1, 4);
  expect(m.emissive.g).toBeCloseTo(0.7, 4);
  expect(m.emissiveIntensity).toBeCloseTo(2, 4);
});

test("the boost scales the authored intensity rather than compounding", () => {
  // Rescaling `emissiveIntensity` in place would compound across style
  // switches. The authored value is kept and the live one is always
  // authored x boost.
  const m = new THREE.MeshStandardMaterial({ name: "Mat_Window" });
  applyPalette(m, {
    Mat_Window: { color: [0, 0, 0], roughness: 1, metalness: 0, emissive: [1, 1, 1] },
  });
  setEmissiveBoost(1.7);
  expect(m.emissiveIntensity).toBeCloseTo(1.7, 4);
  setEmissiveBoost(0.5);
  expect(m.emissiveIntensity).toBeCloseTo(0.5, 4);
  setEmissiveBoost(1.7);
  expect(m.emissiveIntensity).toBeCloseTo(1.7, 4);
});

test("classic turns the glow off outright", () => {
  // `classic` (the board as shipped) needs a boost of zero to turn glow off.
  const m = new THREE.MeshStandardMaterial({ name: "Mat_Window" });
  applyPalette(m, {
    Mat_Window: { color: [0, 0, 0], roughness: 1, metalness: 0, emissive: [1, 1, 1] },
  });
  setEmissiveBoost(0);
  expect(m.emissiveIntensity).toBe(0);
});

test("an asset that loads after the style was chosen arrives already correct", () => {
  // Assets load throughout a board's life; one that used its authored
  // intensity would flash when the next look change applied the boost.
  setEmissiveBoost(1.5);
  const m = new THREE.MeshStandardMaterial({ name: "Mat_Window" });
  applyPalette(m, {
    Mat_Window: {
      color: [0, 0, 0],
      roughness: 1,
      metalness: 0,
      emissive: [1, 1, 1],
      emissiveIntensity: 2,
    },
  });
  expect(m.emissiveIntensity).toBeCloseTo(3, 4);
  expect(currentEmissiveBoost()).toBe(1.5);
});

test("an entry with no emissive leaves the material dark and unregistered", () => {
  // Every exporter entry so far is this case: a stray emissive default would
  // light all 234 materials the moment a style asked for glow.
  const before = glowingMaterialCount();
  const m = new THREE.MeshStandardMaterial({ name: "Mat_Desert" });
  applyPalette(m, palette);
  expect(m.emissive.getHex()).toBe(0x000000);
  expect(glowingMaterialCount()).toBe(before);
});

test("the shipped palette has no self-lit surfaces", () => {
  // A statement of fact: whoever authors the first lit window will see this
  // fail and should look at `BoardLook.emissive`, the multiplier their value
  // is seen through (0 for classic).
  const shipped = JSON.parse(readFileSync(SHIPPED_PALETTE_PATH, "utf8")) as Palette;
  const lit = Object.entries(shipped).filter(([, e]) => e.emissive);
  expect(lit).toEqual([]);
});

test("every material in palette.json is worn by something that ships", () => {
  // The mirror of loader.test.ts's dead-asset guard, for palette.json (32 KB,
  // fetched on every board load). The exporter's `palette_of_open_blend` reads
  // `bpy.data.materials`, so any material in an opened blend lands in the
  // palette whether or not an exported object uses it, and `write_palette`
  // never removes hand edits. Typical leftovers: removed dice materials,
  // excluded `Player_` objects' Mat_Player_*, stale terrain.
  //
  // One direction only. Materials without a palette entry (Mat_Res_*,
  // Mat_RobberSkin_*) are fine: an entry is an override. An override for a
  // material nothing wears can never change a pixel.
  const shipped = JSON.parse(readFileSync(SHIPPED_PALETTE_PATH, "utf8")) as Palette;
  const worn = new Set<string>();
  for (const file of ALL_SHIPPED_GLBS) for (const name of materialsIn(file)) worn.add(name);
  expect(worn.size, "no materials found in the shipped models").toBeGreaterThan(100);

  const dead = Object.keys(shipped).filter((name) => !worn.has(name));
  expect(
    dead,
    `palette.json overrides ${dead.length} material(s) that no shipped .glb wears`,
  ).toEqual([]);
});
