// Compose recipe-built tiles out of hand-authored components.
//
//     make compose-tiles                              # write, then compress
//     node scripts/compose-tiles.ts                   # write only (uncompressed)
//     node scripts/compose-tiles.ts --check           # exit 1 if anything shipped drifted
//     node scripts/compose-tiles.ts --only 'hills' --log /tmp/log.json
//
// Reads `art/recipes/parts.json`, which names every component: the base tiles
// (the shipped `.glb`s, so a base-tile change reaches every variant on the next
// run) with the hero spots authored for each, and the town layouts.
// `art/recipes/<key>.json` is one tile: which ground, which seaward direction,
// which layout, and any per-tile fixes (keep, drop, nudge).
//
// Writes `frontend/public/models/tiles/<key>.glb`, shaped exactly like an
// exported tile (a `Hex_<Terrain>` root, named parts, a `Token_<Terrain>`
// socket), so `models:compress`, `make check-hexes` and every art test see it
// like any other. Also writes `src/lib/board3d/manifest.composed.generated.ts`,
// which `manifest.generated.ts` spreads into `TILES`; neither generator writes
// the other's file.
//
// Deterministic: recipes in sorted order, no clock, no randomness, so the same
// inputs write the same bytes. `--check` (run by `make verify-split`) relies
// on it.
import { mkdtemp, readdir, readFile, rm, writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { spawnSync } from "node:child_process";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { readModel, modelToGlb } from "../src/lib/board3d/compose/io.ts";
import { composeTrade } from "../src/lib/board3d/compose/trade.ts";
import { composeRiver } from "../src/lib/board3d/compose/river.ts";
import {
  parseRecipe,
  terrainForKey,
  type Parts,
  type Recipe,
  type SpotsFile,
  type GroundSpots,
} from "../src/lib/board3d/compose/recipe.ts";
import type { TileModel } from "../src/lib/board3d/compose/model.ts";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const FRONTEND = path.resolve(HERE, "..");
const REPO = path.resolve(FRONTEND, "..");
const RECIPES = path.join(REPO, "art", "recipes");
const TILES = path.join(FRONTEND, "public", "models", "tiles");
const MANIFEST = path.join(FRONTEND, "src", "lib", "board3d", "manifest.composed.generated.ts");

const args = process.argv.slice(2);
const check = args.includes("--check");
const argOf = (flag: string) => {
  const i = args.indexOf(flag);
  return i >= 0 ? args[i + 1] : undefined;
};
const only = argOf("--only");
// The per-tile log (what dropped, which spot each hero took) is what the
// review sheets caption each tile with; it is written beside the review.
const logFile =
  argOf("--log") ?? (check ? undefined : path.join(REPO, ".compose-review", "compose-log.json"));
const outArg = argOf("--out");

export async function loadRecipes(): Promise<{ parts: Parts; recipes: Recipe[] }> {
  const parts = JSON.parse(await readFile(path.join(RECIPES, "parts.json"), "utf8")) as Parts;
  const files = (await readdir(RECIPES))
    .filter((f) => f.endsWith(".json") && f !== "parts.json")
    .sort();
  const recipes = await Promise.all(
    files.map(async (f) =>
      parseRecipe(f.slice(0, -5), JSON.parse(await readFile(path.join(RECIPES, f), "utf8")), parts),
    ),
  );
  return { parts, recipes };
}

function manifestText(entries: [string, [number, number, number] | null][]): string {
  const body: Record<string, unknown> = {};
  for (const [key, socket] of entries)
    body[key] = { resource: key, file: `tiles/${key}.glb`, socket };
  return `// GENERATED by frontend/scripts/compose-tiles.ts -- do not edit.
// Re-run \`make compose-tiles\` after changing anything under art/recipes/.
//
// The recipe-built tiles, spread into \`TILES\` by manifest.generated.ts.
import type { TileEntry } from "./manifest.generated";

export const COMPOSED_TILES: Record<string, TileEntry> = ${JSON.stringify(body, null, 2)};
`;
}

/** A ground's river heroes, with its per-shape `river_spots` where the trade code looks for spots. */
function riverGround(g: GroundSpots | undefined): GroundSpots | undefined {
  if (!g || !g.river_spots || Object.keys(g.river_spots).length === 0) return undefined;
  return { ...g, spots: g.river_spots };
}

const r4 = (v: number) => {
  const x = Math.round(v * 1e4) / 1e4;
  return x === 0 ? 0 : x;
};

async function main() {
  const { parts, recipes } = await loadRecipes();
  const cache = new Map<string, Promise<TileModel>>();
  const model = (rel: string) => {
    let m = cache.get(rel);
    if (!m) cache.set(rel, (m = readModel(path.join(REPO, rel))));
    return m;
  };
  const out = check
    ? await mkdtemp(path.join(os.tmpdir(), "compose-check-"))
    : outArg
      ? path.resolve(outArg)
      : TILES;
  await mkdir(out, { recursive: true });
  const logs: Record<string, unknown> = {};
  const entries: [string, [number, number, number] | null][] = [];
  const json = async <T>(rel: string): Promise<T> =>
    JSON.parse(await readFile(path.join(REPO, rel), "utf8")) as T;
  const tradeSpots =
    parts.trade &&
    recipes.some((r) => r.kind === "trade" && (!only || new RegExp(only).test(r.key)))
      ? await json<SpotsFile>(parts.trade.spots)
      : undefined;
  const riverSpots = parts.river?.spots ? await json<SpotsFile>(parts.river.spots) : undefined;
  for (const r of recipes) {
    const ground = parts.grounds[r.ground];
    const base = await model(ground.file);
    if (!only || new RegExp(only).test(r.key)) {
      const terrain = terrainForKey(r.key);
      const common = { base, terrain, keep: r.keep, drop: r.drop, nudge: r.nudge };
      let result: { model: TileModel; log: { tris: number } };
      let summary: string;
      if (r.kind === "trade") {
        if (!parts.trade || !tradeSpots)
          throw new Error(`${r.key}: parts.json names no trade parts`);
        const DIR = r.variant.toUpperCase();
        const lake = r.ground === "lake";
        const [family, rotate, mirror] = lake ? [null, 0, false] : (tradeSpots.layout?.[DIR] ?? []);
        if (!lake && family == null)
          throw new Error(`${r.key}: spots.json has no layout for ${DIR}`);
        const layoutFile = lake
          ? parts.trade.lake.replace("{dir}", r.variant)
          : parts.trade.layouts[family as string];
        const res = composeTrade({
          ...common,
          layout: await model(layoutFile),
          shared: !lake && parts.trade.shared ? await model(parts.trade.shared) : undefined,
          yard: parts.trade.yard?.[r.ground],
          placement: { rotate: rotate as number, mirror: mirror as boolean },
          dir: DIR,
          ground: tradeSpots.grounds[ground.terrain],
          spots: tradeSpots,
          offset: r.offset,
        });
        result = res;
        const l = res.log;
        summary = `kept ${l.kept}  dropped ${l.dropped.length}  heroes ${l.heroes.map((h) => `${h.hero}:${h.spot}${h.collides ? `!${h.collides}` : ""}`).join(" ") || "-"}  culled ${l.culled.length}`;
      } else {
        const rv = parts.river;
        if (!rv) throw new Error(`${r.key}: parts.json names no river template`);
        const res = composeRiver({
          ...common,
          template: await model(rv.template.replace("{shape}", r.variant)),
          templateBase: await model(parts.grounds[rv.templateGround].file),
          swap: rv.swap[r.ground] ?? {},
          margin: rv.margin?.[r.ground],
          // spots.json keys a river spot by the template's shape, upper case.
          shape: r.variant.toUpperCase(),
          ground: riverGround(riverSpots?.grounds[ground.terrain]),
        });
        result = res;
        const l = res.log;
        summary = `kept ${l.kept}  dropped ${l.dropped.length}  heroes ${l.heroes.map((h) => `${h.hero}:${h.spot}${h.collides ? `!${h.collides}` : ""}`).join(" ") || "-"}`;
      }
      logs[r.key] = result.log;
      await writeFile(path.join(out, `${r.key}.glb`), await modelToGlb(result.model));
      if (!check)
        console.log(`${r.key.padEnd(24)} ${String(result.log.tris).padStart(5)} tris  ${summary}`);
    }
    const s = base.socket?.translation;
    entries.push([r.key, s ? [r4(s[0]), r4(s[1]), r4(s[2])] : null]);
  }
  const manifest = manifestText(entries);
  if (logFile) {
    await mkdir(path.dirname(logFile), { recursive: true });
    await writeFile(logFile, JSON.stringify(logs, null, 1));
  }

  if (!check) {
    if (!outArg) {
      // Delete tiles of removed recipes. (The manifest lists every recipe even
      // under --only.)
      if (!only && existsSync(MANIFEST)) {
        const before = [
          ...(await readFile(MANIFEST, "utf8")).matchAll(/"file": "tiles\/([a-z0-9_]+)\.glb"/g),
        ].map((m) => m[1]);
        const now = new Set(entries.map(([k]) => k));
        for (const k of before)
          if (!now.has(k)) await rm(path.join(TILES, `${k}.glb`), { force: true });
      }
      await writeFile(MANIFEST, manifest);
    }
    return;
  }

  // --check: the fresh files through the same compression pass, then byte for
  // byte against what ships. A drift means a recipe, a part or a base tile
  // changed without `make compose-tiles` being re-run.
  const c = spawnSync(process.execPath, [path.join(HERE, "compress-models.mjs"), out], {
    stdio: "pipe",
  });
  if (c.status !== 0) {
    process.stderr.write(c.stderr);
    process.exit(1);
  }
  let drift = 0;
  for (const r of recipes) {
    if (only && !new RegExp(only).test(r.key)) continue;
    const fresh = await readFile(path.join(out, `${r.key}.glb`));
    const shipped = path.join(TILES, `${r.key}.glb`);
    if (!existsSync(shipped) || !fresh.equals(await readFile(shipped))) {
      console.error(`DRIFT tiles/${r.key}.glb`);
      drift++;
    }
  }
  if (!only && (!existsSync(MANIFEST) || (await readFile(MANIFEST, "utf8")) !== manifest)) {
    console.error("DRIFT manifest.composed.generated.ts");
    drift++;
  }
  await rm(out, { recursive: true, force: true });
  if (drift) {
    console.error(
      `compose-tiles --check: ${drift} file(s) differ from their recipes; run make compose-tiles`,
    );
    process.exit(1);
  }
  console.log(`compose-tiles --check: all ${recipes.length} composed tiles match their recipes`);
}

await main();
