package raiders

import (
	"maps"
	"math/rand/v2"
	"slices"

	"github.com/ftqo/costan.io/engine"
	"github.com/ftqo/costan.io/engine/board"
)

// The battle sweep, run once at the end of every turn, after movement.
//
// Ruling: movement and the sweep never interleave. All riders move, then all
// battles are fought; a player cannot see one result and then move a rider into
// a second battle. Movement is a command during the turn and the sweep is
// generated by OnEvents on the batch that ends it.
//
// Ruling: every seat's riders count, whoever's turn it is. The sweep is
// automatic; the active player cannot decline a battle or choose hexes, and a
// seat can gain prisoners on someone else's turn.
//
// Decision: the order is ascending (Q, R) over landing-eligible hexes. A
// clockwise order round the coast is undefined under Islands, where the coast
// can be several disjoint loops. Order matters (a rider can die in one battle
// and miss the next), so it only needs to be total, deterministic and
// reproducible from the log.

// sweep produces the whole end-of-turn sweep, one fully resolved battle at a
// time. offset is where the first returned event lands in the batch.
//
// It walks local copies of the raider counts and rider positions, because each
// battle's losses change what defends the next hex and none of these events has
// been folded yet.
func (m Module) sweep(s *engine.State, x *Ext, offset int) []engine.Event {
	hexes := x.populationHexes()
	counts := make([]int, len(hexes))
	for i, h := range hexes {
		counts[i] = x.RaidersOn(h)
	}
	riders := make(map[board.Edge]engine.PlayerID, len(x.RiderAt))
	maps.Copy(riders, x.RiderAt)
	var out []engine.Event
	for i, hex := range hexes {
		if counts[i] == 0 {
			continue
		}
		involved := involvedRiders(riders, hex)
		strength := len(involved)
		// A hex is a victory when it holds at least one raider and the riders
		// on its six adjacent paths outnumber them.
		if strength <= counts[i] {
			continue
		}
		rng := engine.PublicRngForSeed(s.PublicSeed, engine.RaidersSeq(s.NextSeq+offset+len(out)))
		d := battleData{
			Hex: hex, Raiders: counts[i], Strength: strength, Involved: involved,
		}
		gold := map[engine.PlayerID]int{}
		d.Prisoners = splitPrisoners(rng, involved, counts[i], gold)
		// Losses are applied right after the battle that caused them, so a
		// rider lost at one hex cannot defend the next.
		d.Die = rng.IntN(6) + 1
		d.Dir = (d.Die - 1) % 3
		d.Lost = lossesFor(hex, involved, d.Dir)
		for _, l := range d.Lost {
			gold[l.Player] += goldPerLoss
		}
		d.Gold = seatCounts(gold, len(s.Players))
		out = append(out, engine.NewEvent(EvBattle, d))

		counts[i] = 0
		for _, l := range d.Lost {
			delete(riders, l.E)
		}
	}
	return out
}

// involvedRiders is every rider standing on one of the hex's six paths, in seat
// then path order. The involved seats are those with at least one of these.
func involvedRiders(riders map[board.Edge]engine.PlayerID, h board.Hex) []riderAt {
	var out []riderAt
	for _, ed := range h.Edges() {
		if owner, ok := riders[ed]; ok {
			out = append(out, riderAt{Player: owner, E: ed})
		}
	}
	slices.SortStableFunc(out, func(a, b riderAt) int {
		if a.Player != b.Player {
			return int(a.Player - b.Player)
		}
		switch {
		case edgeLess(a.E, b.E):
			return -1
		case edgeLess(b.E, a.E):
			return 1
		}
		return 0
	})
	return out
}

// seatsOf is the distinct seats in an involved list, in seat order.
func seatsOf(in []riderAt) []engine.PlayerID {
	var out []engine.PlayerID
	for _, r := range in {
		if !slices.Contains(out, r.Player) {
			out = append(out, r.Player)
		}
	}
	slices.Sort(out)
	return out
}

// splitPrisoners settles the prisoner split and records the consolation gold.
//
// Every raider on the hex becomes a prisoner and never returns to the supply.
// The involved seats take them:
//
//   - One involved seat: it takes all of them.
//   - Several seats, at least as many prisoners as seats: one each, in seat
//     order.
//   - Several seats, fewer prisoners than seats: each involved seat rolls; the
//     highest rollers take the prisoners, re-rolling ties among them. Any seat
//     that rolls and comes away with nothing takes 3 gold.
//   - A prisoner left over after everyone has one goes to the seat with the most
//     involved riders; a tie there is settled by a roll among the tied seats, and
//     the losers take 3 gold each.
//
// At most three raiders stand on one hex, so with two or more seats there is at
// most one leftover.
func splitPrisoners(rng *rand.Rand, involved []riderAt, n int, gold map[engine.PlayerID]int) []seatCount {
	seats := seatsOf(involved)
	take := map[engine.PlayerID]int{}
	switch {
	case len(seats) == 0 || n == 0:
		return nil
	case len(seats) == 1:
		take[seats[0]] = n
	case n < len(seats):
		winners := pickByRoll(rng, seats, n)
		for _, p := range winners {
			take[p]++
		}
		for _, p := range seats {
			if take[p] == 0 {
				gold[p] += goldPerLoss
			}
		}
	default:
		for _, p := range seats {
			take[p] = 1
		}
		for left := n - len(seats); left > 0; left-- {
			p := mostInvolved(rng, involved, seats, gold)
			take[p]++
		}
	}
	return seatCountsOf(take, seats)
}

// mostInvolved names the seat with the most riders in this battle, settling a
// tie by a roll among the tied seats and paying the losers 3 gold each.
func mostInvolved(rng *rand.Rand, involved []riderAt, seats []engine.PlayerID, gold map[engine.PlayerID]int) engine.PlayerID {
	count := map[engine.PlayerID]int{}
	for _, r := range involved {
		count[r.Player]++
	}
	best := 0
	for _, p := range seats {
		if count[p] > best {
			best = count[p]
		}
	}
	var tied []engine.PlayerID
	for _, p := range seats {
		if count[p] == best {
			tied = append(tied, p)
		}
	}
	if len(tied) == 1 {
		return tied[0]
	}
	winners := pickByRoll(rng, tied, 1)
	if len(winners) == 0 {
		winners = tied[:1]
	}
	for _, p := range tied {
		if p != winners[0] {
			gold[p] += goldPerLoss
		}
	}
	return winners[0]
}

// pickByRoll picks `take` seats out of cands by rolling a die each, highest
// first, re-rolling ties among the tied.
//
// Deterministic in rng and bounded, since this runs inside a pure fold; the
// unreachable fallback takes the lowest seats in order.
func pickByRoll(rng *rand.Rand, cands []engine.PlayerID, take int) []engine.PlayerID {
	winners := make([]engine.PlayerID, 0, take)
	pool := slices.Clone(cands)
	for range 64 {
		if len(winners) >= take || len(pool) == 0 {
			break
		}
		best := 0
		var top []engine.PlayerID
		for _, p := range pool {
			r := rng.IntN(6) + 1
			switch {
			case r > best:
				best, top = r, []engine.PlayerID{p}
			case r == best:
				top = append(top, p)
			}
		}
		if len(top) <= take-len(winners) {
			winners = append(winners, top...)
			pool = slices.DeleteFunc(pool, func(q engine.PlayerID) bool { return slices.Contains(top, q) })
			continue
		}
		pool = top // more tied at the top than places left: re-roll among them
	}
	for i := 0; len(winners) < take && i < len(pool); i++ {
		winners = append(winners, pool[i])
	}
	slices.Sort(winners)
	return winners
}

// lossesFor is the riders a victory costs.
//
// After each victory one die is rolled. Its face names one of the three edge
// directions of the hex: the path with that face and the path opposite it. The
// direction is (die - 1) mod 3, and Hex.Edges() orders the six so index and
// index+3 are opposite.
//
// Every rider involved in that victory on a path of that direction returns to
// its owner's supply, and its owner takes 3 gold for each. Riders elsewhere are
// untouched.
func lossesFor(h board.Hex, involved []riderAt, dir int) []riderAt {
	edges := h.Edges()
	hit := map[board.Edge]bool{}
	for i, ed := range edges {
		if i%3 == dir {
			hit[ed] = true
		}
	}
	var out []riderAt
	for _, r := range involved {
		if hit[r.E] {
			out = append(out, r)
		}
	}
	return out
}

// seatCountsOf renders a per-seat tally in seat order, dropping the zeroes, so
// the event's bytes never depend on Go's map ordering.
func seatCountsOf(m map[engine.PlayerID]int, seats []engine.PlayerID) []seatCount {
	var out []seatCount
	for _, p := range seats {
		if m[p] > 0 {
			out = append(out, seatCount{Player: p, Count: m[p]})
		}
	}
	return out
}

// seatCounts is seatCountsOf over every seat at the table, for a tally whose
// seats are not already listed.
func seatCounts(m map[engine.PlayerID]int, players int) []seatCount {
	var out []seatCount
	for i := range players {
		p := engine.PlayerID(i)
		if m[p] > 0 {
			out = append(out, seatCount{Player: p, Count: m[p]})
		}
	}
	return out
}
